name: 'Update pubspec version'
description: 'This action updates the pubspec version with different strategies'
branding:
  color: white
  icon: 'package'
inputs:
  strategy:
    description: 'The strategy to use to update the version. Can be major, minor, patch, or none.'
    required: false
    default: 'none'
  bump-build:
    description: 'Whether to bump the build number.'
    required: false
    default: 'false'
  path:
    description: 'The path to the pubspec.yaml file.'
    required: false
    default: './pubspec.yaml'
outputs:
  old-version:
    description: 'The old version.'
  new-version:
    description: 'The new version.'
runs:
  using: 'node20'
  main: 'dist/index.js'